"""
Constants used inside tests.

.. moduleauthor:: Harvey Lelliott (flip-dots) <harveylelliott@duck.com>
"""

from bleak import BLEDevice

from SolixBLE import const, prime_device

MOCK_DEVICE_NAME = "Mock Device"
"""
Mock device name used to emulate Anker devices for tests.
"""

MOCK_DEVICE_ADDRESS = "AA:BB:CC:DD:EE:FF"
"""
Mock bluetooth address used to emulate Anker devices for tests.
"""

MOCK_BLE_DEVICE = BLEDevice(
    address=MOCK_DEVICE_ADDRESS,
    name=MOCK_DEVICE_NAME,
    details={},
    rssi=-1,
)
"""
Mock BLEDevice used to emulate Anker devices for tests.
"""


NEGOTIATION_RESPONSES_PRIME: dict[str, list[str]] = {
    # Stages 0-3 are built live (encrypted with the static key) under the frozen_time
    # fixture; regenerate these literals if that fixture's clock changes.
    "ff09200003000140010a827d7f6a531e146637b9a16158348e7baa5e5ebeac25": [
        "ff091e000300014801ab273ed3e27270c3f4d676ac7d69a00572793732a6",
    ],
    "ff09270003000140030a827d7f6a538ab3de100ac9bb9a57744bd99325c8ca77e287ab3672438d": [
        "ff092b000300014803ab273ed0443800b35db54c6d4a6ec3d48171a04ea7ebce8bf749e5e48c5d991a5e67",
    ],
    "ff09200003000140290a827d7f6a531e146637b9a16158348e7baa5e5ebeac0d": [
        "ff0958000300014829ab273ed144326ada9fc66fa02508c5ddf549ade014d1eeb252fea1057c15b00985ab8a724fa3830e8e5b27acbaa1224fd2172c0439d27aaf9e62a66bda5c41c424f23c5c8d7df8d3b89422ddff2266",
    ],
    "ff092d0003000140050a827d7f6a538ab3de100ae04aca6791257881e2e19a569ca195a8b15d5d0edb66230274": [
        "ff091b000300014805abab709a595a803dd04246b78a927453cf65",
    ],
    prime_device.NEGOTIATION_COMMAND_4: [
        "ff095d000300014821ab277fc01de436d341de628c79c1384d0aea25ce030622fa3ca0808ce5d1b7365ec1b1753a11ab78fba3ca07dda95cd57c93d1267b1222bef9908f7633a758ab924eba63ee01e715be5b9c3b082e6d81c2204241",
    ],
    # These packets below are dynamically generated by the library unlike previous
    # negotiation packets as past stage 5 negotiations the packets use the shared
    # secret for encryption which is different from device to device due to different
    # public keys. This is why constants are not used. But we can use constants for
    # the earlier packets which use static keys.
    "ff093e00030001402257ecdb8c563500c8f858e0ba047121614e2bdfd20d2f39ba3580e4010109a3de3d43936a2ddbda49225d4b02a31e62f8ce022210c1": [
        "ff091b000300014822f60b45600839b2c171b33dc5790ed64ae32d",
    ],
    "ff094600030001402757ecdb8c563501e8cf6185d8c4035707377af9af3a2e40b02b86e7531974f1c22440de6e43705566b77cf94035eb28eaef98a9f67aa3810abc40de8409": [
        "ff091b000300014827f60b45600839b2c171b33dc5790ed64ae328",
    ],
    "ff09230003000f420057e9b8dfde1e0e409121ab89a1119c200c35523e9f0118bcc7fa": [],
    "ff092c0003000f420a57e9b883d958e48e5d5ae1bb5f63269f96779ebdbf43bd5ab4babfae73120d63897d15": [],
    "ff092f0003000f420b57e9b883d058a2ccfb4de1bba16764cc1e5c371a30deae32e05babe273066746b24b06c4da27": [],
}
"""
This maps the expected commands sent by the library to what my Anker Prime 160w
charger sends in response. Its used to emulate it for testing negotiations.
"""


# MagGo 3-in-1 only subscribes post-connect (a single 4200); it sends none of the
# 4027 registration, 420a getter, or 420b realtime trigger, so drop those from the
# shared prime negotiation to match its shorter post-connect sequence.
NEGOTIATION_RESPONSES_MAGGO: dict[str, list[str]] = {
    frame: responses
    for frame, responses in NEGOTIATION_RESPONSES_PRIME.items()
    if frame[14:18] not in ("4027", "420a", "420b")
}


# Stages 0-3 are built live (UUID-free, live ``a1`` timestamp) under the ``frozen_time``
# fixture -- regenerate these literals if that fixture's clock changes. Stages 4 (static
# pubkey) and 5 (frozen confer) are unchanged, so they still key off the constants.
NEGOTIATION_RESPONSES_SOLIX: dict[str, list[str]] = {
    "ff0910000300010001a10442ad8c694a": ["ff090e00030001080100a1010152"],
    "ff0917000300010003a10442ad8c69a30120a40200f09b": [
        "ff091b00030001080300a10102a202fd00a30144a40101a50102ff",
    ],
    "ff0910000300010029a10442ad8c6962": [
        "ff093800030001082900a10103a2054553503332a307302e302e302e33a41041504339464530453237333030323735a506f49d8a104e0c9a",
    ],
    "ff091a000300010005a10442ad8c69a30120a40200f0a5014074": ["ff090b00030001080500f2"],
    const.NEGOTIATION_COMMAND_4: [
        "ff094d00030001082100a140b2ade5cac4f4a0c1307e44a0e9c5363cb21e4c8485ee324c23be949fa5d5929a75e57da3207c948a0c366ca9ea1ab2cb8e57d2d046a6ebefe5d96adb5d4cb35039",
    ],
    # Stage 5 is now the live CBC 4022 confer (a1 timestamp + local tz), reproducible
    # here because frozen_time pins both the clock and the timezone.
    "ff093a000300014022903b2e4bc916b8515b35b6c171fbe160f1be2ffe9874600a8582c2a937c9dfdadf867985507518af4229e35cb7fe30f5a6": [],
}
"""
This maps the expected commands sent by the library to what my Anker Solix C300
sends in response. Its used to emulate it for testing negotiations.
"""
